### ISSUE TITLE
newtab.show & newtab.hide from newTab.properties

### ISSUE THREAD

**Issue by JustOff** [MoonchildProductions/pale-moon-localization#146]
newtab.show & newtab.hide from newTab.properties looks like unreferred, safe to remove?

**Comment by janekptacijarabaci** [comment]
In my opinion you are wrong:

See also:
https://github.com/MoonchildProductions/Pale-Moon/blob/27.0_RelBranch/browser/base/content/newtab/newTab.js#L35
https://github.com/MoonchildProductions/Pale-Moon/blob/27.0_RelBranch/browser/base/content/newtab/page.js#L109
vs.
https://hg.mozilla.org/mozilla-central/rev/999c74d2ab23

Not always the whole string!

**Comment by JustOff** [comment]
@janekptacijarabaci, thanks! Now I see.

Then, I'd like to suggest change those properties from:

newtab.show=Show the new tab page
newtab.hide=Hide the new tab page

to

newtab.show=Show classic new tab page
newtab.hide=Hide classic new tab page

**Comment by wolfbeast** [comment]
... Why does it need changing? There's nothing "classic" about it.

**Comment by JustOff** [comment]
I could not even understand "Show/hide the new tab page", until @janekptacijarabaci pointed me to it. And yes, it's classic to show last visited/most popular sites, isn't it? And what means the phrase "Show/hide the new tab page" on the "new tab page" itself?)

**Comment by wolfbeast** [comment]
It's the text for the small icon top-right on the page itself to show/hide the actual new tab page (faking a blank page when "hidden") -- You can blame Mozilla for that one.

**Comment by JustOff** [comment]
But even Mozilla calls it "Classic" or "Blank":

![firefox_2016-11-11_23-55-02](https://cloud.githubusercontent.com/assets/340855/20231433/7f8daf2a-a86a-11e6-9a7f-deee5615a1dd.png)

**Comment by wolfbeast** [comment]
# We're not Firefox.
We don't have "enhanced" tiles (which is just another word for "with ads").
