### ISSUE TITLE
Sync with source

### ISSUE THREAD

**Issue by JustOff** [MoonchildProductions/pale-moon-localization#148]
As we need to track changes like [this](https://github.com/MoonchildProductions/Pale-Moon/pull/676#issuecomment-260448099), I'd like to know how this repo is usually syncing with [source](https://github.com/MoonchildProductions/Pale-Moon)?

**Comment by wolfbeast** [comment]
There is no automatic synching. 
Whenever the source strings update, a build needs to be made, and then the resulting packages en-US language pack needs to be dropped in here.
I know crowdin has some integration options as well but I haven't had the time to check out how it works.

**Comment by JustOff** [comment]
Do I need to set up full build environment to make language pack?

**Comment by JustOff** [comment]
As far as I understand from [your instruction](https://forum.palemoon.org/viewtopic.php?f=19&t=13556) and [MDN guide](https://developer.mozilla.org/en-US/docs/Mozilla/Creating_a_language_pack), Mozilla build tools 2.1.0 without VS2013 should be sufficient to make language pack, but unfortunately I can't handle it by myself.

Could you please provide step-by-step howto, as you made it for full build?

**Comment by JustOff** [comment]
After some experimentation, I found that under WIN we need full build.
