### ISSUE TITLE
Prepare langpacks for 27.5.* releases

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/pale-moon-localization#197]
What it says on the tin.
I don't know if there are any outstanding/pending translations for the current strings but if so, they need to be ironed out and langpacks made final to push out before 27.5.0.

- [x] Fix outstanding strings + verify translations
- [x] Final versioning
- [x] Release packaging run
- [x] Publish

**Comment by JustOff** [comment]
What is the deadline?

**Comment by wolfbeast** [comment]
I'd prefer to have these out next week, so I can publish the browser the week after at the latest.

**Comment by JustOff** [comment]
Language Packs for Pale Moon 27.5.0 are almost ready, except for a few untranslated strings in Chinese Simplified, Dutch, Greek and Swedish. I just built pre-release packages from the current tree and put the corresponding announce on the forum. I'll repeat this once again if any updates will come before September 24, and 'll update this issue.

**Comment by wolfbeast** [comment]
I can help with Dutch.

**Comment by JustOff** [comment]
Chinese Simplified, Dutch, Greek and Swedish locales were finished and uploaded to GigHib. I just built pre-release packages once again and put the last chance announcement on the forum.

**Comment by wolfbeast** [comment]
Okay -- I've set the browser release date to the 26th, so langpacks should be published no later than Friday.

**Comment by JustOff** [comment]
The language packs are ready for release.

**Comment by wolfbeast** [comment]
Is Ukranian (uk) release-ready?

**Comment by wolfbeast** [comment]
Ah wait never mind, I see you added it as an inactive language.
