### ISSUE TITLE
Universal location of Preferences/Options

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/pale-moon-localization#213]
Taking this out of commit comments because it's a PITA to find.

@MikkCZ wrote:
> Bigger problem I see for localizers, for whom PM has lowered the ability to actually localize and not only translate, when they are now forced to choose a single term and "support" a single platform only. PM does not state, which platform is the main target. For English Preferences may be OK on Windows, but for Czech bringing the terms from the Lin/Mac world to Windows may sound awkward, or vice versa. You should hope everyone does it consistently and with the right platform terminology in mind.

> @wolfbeast I understood from the tickets you made the decision for the change. Was there a reason to force this on all locales other than simplifying the code?

There are several issues with not having a uniform way to access specific product features depending on platform, e.g. to provide instructions or support. It's madness to have to design an application UI with unique ways to access specific features depending on target platform. Having a unified name (which was the case initially in Mozilla products anyway, as it was all called "preferences") makes the application less ambiguous to use and provide support for.
The fact that it simplifies code under the hood is only a secondary bonus, but not the reason for this change.

As for "forcing it" on all locales, this is not forcing anything -- it is an application UI change that localizers have to follow. Localizers do not determine the layout of the application they localize; that is the developer's task.

**Comment by MikkCZ** [comment]
> As for "forcing it" on all locales, this is not forcing anything -- it is an application UI change that localizers have to follow. Localizers do not determine the layout of the application they localize; that is the developer's task.

That's true for the location, but I don't think that's true for the strings.

> Having a unified name (which was the case initially in Mozilla products anyway, as it was all called "preferences")

But it does not for several years anymore, the changed code is the evidence. ;) 

> makes the application less ambiguous to use and provide support for.

I think more for support than to use. As mentioned in the original comment, it makes it easier for those who travel between the platforms and do not expect the applications to follow the platform habits (either items location or terminology). But not for the users who use a single platform only and are used on its paradigms. The decision is a trade off between the browser fitting into the platform and being easier to translate and for support. Intentionally I didn't said to localize, because it will be simpler only for the cost that you cannot localize for all platforms.

As for support, do you officially provide support in any other language than English?

**Comment by wolfbeast** [comment]
Support is provided regardless of language, so your entire argumentation is moot.
Yes, it's a trade-off between OS integration and an unambiguous interface. I think having an unambiguous interface is more important than whatever paradigms the target platform uses. This is where definitions about intuitive UIs have internal conflict, and the only way out of that conflict is to make a decision what to use. I choose to prioritize an unambiguous UI over OS integration here.

**Comment by MikkCZ** [comment]
> Support is provided regardless of language

How do you speak with the user? In English? If you navigate to the correct menus and settings in English, you use Options/Preferences as you want, but the users of localized version will always have the localized term, so a different term. Using the same term on all platforms simplifies the support only when the support is provided in the same language as the UI of the user is.

In case you have support in English only, the unification of the terms Options/Preferences actually helps users with English builds only. Then I would vote to provide two different strings for the different platforms so localizers can decide for their languages independently on their priorities, or based on the feedback from contributors providing support in their language.

**Comment by wolfbeast** [comment]
No. Using one term and one translated term simplified support. having terms be different depending on "whether the translator feels like using either 1 or 2 terms" makes it more difficult to provide support.

I'm done with this discussion -- I'm not going to revert this, and you should use "preferences" as a source term and unilaterally translate it to a single target term in whatever language that is the closest established translation for it (or closest literal translation if there are multiple, equally-used translations). If you don't like it, then that's too bad.
