### ISSUE TITLE
Prepare for Pale Moon 28 localization

### ISSUE THREAD

**Issue by JustOff** [MoonchildProductions/pale-moon-localization#223]
- [x] Set-up [CrowdIn Console Client](https://support.crowdin.com/cli-tool/)
- [x] Experiment with [CrowdIn Versions Management](https://support.crowdin.com/versions-management/)
- [x] Investigate possibility to use [Firefox language packs](https://addons.mozilla.org/en-US/firefox/language-tools/) to pre-fill missed translations
- [x] Investigate merge and sync of the sources (where CrowdIn comments go?)
- [x] Prepare and test migration scripts
- [x] Deal with the account plan quota on CrowdIn
- [x] Perform a test migration to estimate the number of strings left untranslated.
- [x] Choose the optimal migration strategy
- [x] Perform a final test of the migration scripts
- [x] Perform the migration
  * [x] Upload latest v27 updates to GitHub 
  * [x] Export and save "clean" v27 translations (without substitutions from en-US)
  * [x] Move `preferences\aboutPermissions.*` to `..\permissions\`
  * [x] Remove files no longer used in v28
  * [x] Add new files for v28
  * [x] Update existing files to match v28
  * [x] Pre-fll new strings with the data from Firefox 52 langpacks
- [x] Verify the results
- [x] Hide the strings that are not supposed to be translated
- [x] Create the list of string that require to be updated after import from Firefox
- [x] Create the list of new string that use plurals
- [x] Post an announcement on the forum

**Comment by JustOff** [comment]
@wolfbeast, today I tried to feed CrowdIn with the PM28 strings, but got the message that the account plan quota is exceeded:

![palemoon_2018-06-15_20-53-35](https://user-images.githubusercontent.com/340855/41482954-f001d6d4-70df-11e8-8153-2bffbb100bfc.png)

Could you please contact them and ask how to resolve this issue?

**Comment by wolfbeast** [comment]
Please understand we are on a free Open Source tier here; our current quota is already larger than normal for that because of what I arranged with them.

If you want to move to v28, then you cannot just upload the new strings _in addition_ to what there is; you will have to replace the current files with the new ones, because we can't simply double our quota needs suddenly... Previously translated strings will remain and we have our TM (translation memory) that has been built up with our translations, so it will allow us to quickly populate fuzzy-matches if strings have changed.
Before you can, we have to make sure we are done with v27 completely.

Don't do anything yet though, I will contact them and ask what can be done to resolve this issue.

**Comment by wolfbeast** [comment]
It looks like they added a feature called version branches which we may be able to use. We may still need a bit more quota though because of the extra room needed for e.g. added devtools and DRM crap, but I may be able to work something out there.

**Comment by wolfbeast** [comment]
**They doubled our quota.**

Important to note though is that if you work in a different folder that comments with specific strings aren't retained (because they are considered different) so we either have to try working with the version branch feature, or simply overwrite what is there with the new one and not work parallel (the latter is probably simpler, and we can just call 27.9.3 the final langpack versions for 27.*).

What do you think?

**Comment by JustOff** [comment]
> They doubled our quota.

Oh, good news! Let's just hope this is enough ;)

As you can see from the tasklist above, I have already tried different strategies using both independent and version branches, but have not yet found the best option.

I'm going to continue my experiments further and report the results.

**Comment by JustOff** [comment]
Well, the double quota is enough:

v27 - 8952 strings
v28 - 8028 strings

**Comment by JustOff** [comment]
I performed a test migration of the translation from v27 to v28, taking into account the additional strings from FF52, and here is the result:

| v27 | v27 -> v28 | v52 -> v28 | Untranslated strings |
| ---- | --- | ---- | --- |
| 100% | 70%<sup>1</sup> /  81%<sup>2</sup> |  99%<sup>1</sup> /  99%<sup>2</sup> | 17<sup>1</sup> / 20<sup>2</sup> |

<sup>1/2</sup> - browser/chrome folders data

I think this is near perfect, but the choice of migration strategy still requires additional experiments.

**Comment by wolfbeast** [comment]
Looks good at the very least. Even if the merge is 99%, all translations should be checked to make sure it's uniform in style and wording, which may require a good number of edits.

**Comment by JustOff** [comment]
I performed several additional experiments and here are my conclusions:

* The CrowdIn version branches feature, as it's designed, does not fit our localization workflow
* It makes no sense to keep both PM27 and PM28 strings on CrowdIn at the same time (this will only be a waste of their resources and will double the time for building langpacks)
* The best strategy is to simply update current sources on CrowdIn from PM27 to PM28; this allows us to retain the entire history and comments from the very beginning
* If we need to make any updates to the PM27 langpacks, we can just add the necessary strings back to CrowdIn (we can always import full PM27 tree back, although I can't imagine why this might be needed)

@wolfbeast, what do you say?

**Comment by wolfbeast** [comment]
As I already said in https://github.com/MoonchildProductions/pale-moon-localization/issues/223#issuecomment-397804294 -- updating the current strings to v28 has my preference. I don't see any realistic need to update any strings in v27 beyond this point in time.

**Comment by JustOff** [comment]
Ok, now I think I'm ready to perform the migration from v27 to v28 on CrowdIn, and I'm going to do it this evening.

**Comment by JustOff** [comment]
The migration is complete! It's took me freaking 3 hours of spider-work, but I finally got over it, and the initial check went well. 

It's enough for today, I will continue the detailed inspection and further actions tomorrow.

**Comment by JustOff** [comment]
The task is finished.

I hope translators will take advantage of the opportunity to start their work long before the release.
