### ISSUE TITLE
Philippine language pack: choosing the right name and language code

### ISSUE THREAD

**Issue by JustOff** [MoonchildProductions/pale-moon-localization#224]
Since the Philippine language pack has reached the release ready state we need to choose the right name and language code under which it will be published.

Due to [the fact](https://pontoon.mozilla.org/tl/) that the [Mozilla Philippines Localization Team](https://wiki.mozilla.org/L10n:Teams:tl) uses `tl` as a language code and `Tagalog` as a name, I originally intended to do the same for Pale Moon and that's how it is organized in our repository at the moment.

However, @FranklinDM considers this to be incorrect and here are his arguments:

> I've done research about this topic, questions from a few people, and some information from the govt. itself: I disagree with their current decision (based on what they're discussing in Google Groups, which is `Tagalog` vs. `Filipino`) that to just choose `Tagalog` because people are already used to that term. If websites would check for it then let's just declare it in our list of accept-language header (in fact it's already listed there at the moment). In that way, sites would still present their content in `TL` if they won't accept `FIL`. I think we shouldn't have switched from `Filipino` -> `Tagalog` since `FIL` is our national language, it is the standard, has a different alphabet system (`TL` - ABAKADA, `FIL`- ABCD), and a more liberal way of borrowing words from other languages (like English and the other languages of the Philippines) especially in the Technology and Science field. It is also the tag being used by other known companies (e.g. Facebook, Microsoft, Google, and more). I also noticed that translation suggestions appear in `Fil`, but not in `TL`.

Actually, we have three different attributes for every language: the language name (used in description), the internal locale code (equal to the name of the language pack file) and the list of locales that browser is sending in the Accept header. 

I could not find out how is Edge doing, but on the site Microsoft uses `Tagalog/fil-ph`, and Wikipedia uses `Tagalog/tl`; here is the comparison table for the rest of browsers:

|     | Language name | Locale (internal) | Accept header | 
| -------- | ----------------- | ------ | -------------- |
| Mozilla   | Tagalog | tl | tl-PH, tl |
| Chrome | Filipino | fil | fil |
| Pale Moon (current) | Tagalog | tl | tl, fil |
| | | | |
| Pale Moon (proposal) | Filipino | fil | tl, fil |

In any case, the most important is the list of locales for the Accept header, and Pale Moon already uses the solution, which covers both variants used by Mozilla and Chrome. 

All we have to decide is what to choose for the language name and locale code internally: `Tagalog/tl` or `Filipino/fil`.

**Comment by wolfbeast** [comment]
I think you're confusing two things here. Tagalog/`tl` is an ISO 639-1 code (which is what we normally use for our language packs). Filipino/`fil` is an ISO 639-2 code. Tagalog's ISO639-2 code is actually `tgl`, not `tl`.

So the real question would be:

1. Are Tagalog and Filipino _really_ 2 different languages, or just _flavors_? (If flavors, then `tl-PH` would be correct if we stick to ISO 639-1 as we have been)
2. If they are actually to be considered two different languages and translation was made in crowdin as Tagalog, but was actually translated to Filipino, then that should be corrected there and the language pack should be `fil`

I'm a linguist myself, but unfortunately not at all familiar with that family of languages. Loaning more words from foreign languages and other practical differences in formality would suggest number 1 is the case, but different alphabet would suggest a favor of number 2, which inherently also means that it has no ISO 639-1 code associated with it.
**However**: I did some research myself and Abakada has actually been superseded (in 1987 officially) by the [modern Filipino alphabet](https://en.wikipedia.org/wiki/Filipino_alphabet), so Tagalog and Filipino (and other autochtone languages of the islands) are currently uniformly written using the same alphabet. So I think the number 1 solution would be correct (Tagalog-Philippines, `tl-PH`). This also avoids having to mix ISO standards.

**Comment by JustOff** [comment]
So, based the arguments provided by @wolfbeast, it seems it's better to release Philippine language pack as `tl-ph/Tagalog`.

@wolfbeast, since we are not expecting to have any other flavors of Tagalog, can we just use `tl/Tagalog` as internal names, but extend the list of locales for the Accept header from `tl, fil` to `tl-PH, tl, fil`? This way we will be in parity with all other browsers and simplify the synchronizing with CrowdIn.

@FranklinDM, are you ok with this decision or have any additional considerations?

**Comment by wolfbeast** [comment]
As far as I know you can always use a flavor, and if no match it will match the root language automatically (so `tl-PH` would cover both exactly that locale and the `tl` root) but to be sure you can explicitly list all, of course. As for friendly name, `Filipino/Tagalog` is probly best.

**Comment by wolfbeast** [comment]
I wouldn't make 2 versions, that's overkill. If there's a choice, then using properly accented characters is _always_ preferred over non-accented workarounds -- we have UTF-8 for a reason ;)
Same goes for German, for example (ö vs. oe, ß versus ss, etc.).
So, if you don't mind, please change the language pack to use accented characters.

**Comment by FranklinDM** [comment]
The reason why I refrained from placing accent marks in the first place was to be consistent/the same with the other localization project (at Mozilla). I'll try but it might take a few days or so.

**Comment by JustOff** [comment]
Filipino (Tagalog) language pack is finally ready for release.

@wolfbeast, could you please pack and publish it?

**Comment by wolfbeast** [comment]
Actually, I think we should make sure to use the proposed wording for the add-on blocklist for soft-blocked items, so people don't explode over it again.

**Comment by FranklinDM** [comment]
Filipino (Tagalog) is now updated accordingly to these changes.

**Comment by JustOff** [comment]
[Published](https://addons.palemoon.org/language-packs/).
