### ISSUE TITLE
27.9 language pack update

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/pale-moon-localization#227]
We need an update for language packs, because:
- https://github.com/MoonchildProductions/Pale-Moon/commit/5c1cd01e50102b9f37865359e792953b37d9db2e
- Filipino/Tagalog addition.

We should roll these two items into on point release update.

- [x] Get all localizations to use the different softblocked wording
- [x] Finalize Filipino
- [x] Final versioning
- [x] Pack
- [x] Publish

1-2 @JustOff 
3-5 @wolfbeast

**Comment by wolfbeast** [comment]
Ugh -- so the dialog box for blocked items have other strings in a .dtd
Those need adjusted and translated, as well.

**Comment by wolfbeast** [comment]
https://github.com/MoonchildProductions/Pale-Moon/commit/4e6937b4d9f14db9cca1036733413e3abcc1da13
and
https://github.com/MoonchildProductions/Pale-Moon/commit/94ea88ba5785e62e67fd391a10187bc6bb8d9198

**Comment by wolfbeast** [comment]
Sorry about the mess, @JustOff

**Comment by JustOff** [comment]
No worries, are these changes final now?

**Comment by wolfbeast** [comment]
Yes they are!

**Comment by wolfbeast** [comment]
I've translated Dutch and German -- the German should be proofed by someone native since my grammar is a bit rusty.

**Comment by JustOff** [comment]
All but Chinese language packs are ready; let's give them a couple more days.

**Comment by JustOff** [comment]
Unfortunately, the situation with the Chinese langpack has not changed over the weekend, and I see no reason to delay further the publication of all language packs due to one.

Since this update is a special case, I would like to discuss the next step: is it better to temporarily keep the previous translation or use the original strings in English? I am inclined to the first option.

**Comment by wolfbeast** [comment]
Temporarily keep the original Chinese strings in this case.

**Comment by JustOff** [comment]
My part is done, now it's your turn.

**Comment by wolfbeast** [comment]
I thought we agreed on tl-PH?

**Comment by wolfbeast** [comment]
I'll just publish as tl -- can't be arsed to re-do the architecture for it for something that will probably never see other variants used of it anyway.

**Comment by JustOff** [comment]
Oops, I was absolutely sure we agreed to use `tl`, just like we use `el` and `uk` instead of `el-GR` and `uk-UA`, since of no other variants are expected. This also simplifies integration with CrowdIn.

**Comment by wolfbeast** [comment]
Yeah like I said no other variants are expected. Just makes part of the discussion we had moot ;)
