### ISSUE TITLE
27.9 language pack update (zh-CN softblocked wording)

### ISSUE THREAD

**Issue by JustOff** [MoonchildProductions/pale-moon-localization#230]
This is follow-up to #227 with the Chinese langpack [updated strings](https://github.com/MoonchildProductions/pale-moon-localization/issues/227#issuecomment-390698398) for the [softblocked wording](https://github.com/MoonchildProductions/Pale-Moon/commit/5c1cd01e50102b9f37865359e792953b37d9db2e).

- [x] Get the `zh-CN` localization to use the different softblocked wording
- [x] Final versioning
- [x] Pack
- [x] Publish

**Comment by wolfbeast** [comment]
I backed out the CS changes before packing and publishing.

**Comment by JustOff** [comment]
Thank you.
