### ISSUE TITLE
Publish final v27 langpacks

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/pale-moon-localization#233]
@JustOff if I understand correctly the repo is set to have one more update of language packs for v27?

If so, we should do that soon, then clear the way for v28.
Please let me know if there's anything that still needs doing or if the current RC is good to go...

**Comment by JustOff** [comment]
27.9.4 RC1 and RC2 do not include any significant updates, so an additional v27 release isn't required.

PS: The way for v28 is absolutely clear, and I'm going to build 28.0.0 RC1 around July 2.
