### ISSUE TITLE
Prepare langpacks for 28.0.* release

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/pale-moon-localization#237]
It's that time! With the planned release 2 weeks away, we should finalize the language packs.

- [x] Fix outstanding strings + verify translations
- [x] Final versioning
- [x] Release packaging run
- [x] Publish

**Comment by JustOff** [comment]
The sources on CrowdIn were synced with [the tree frozen against string changes](https://github.com/MoonchildProductions/UXP/tree/803dfd7b1f24f8f455b888f814080ec2e0391621).

**Comment by JustOff** [comment]
I just [updated all currently released languages](https://crowdin.com/project/pale-moon/activity_stream) with data taken from Firefox :cowboy_hat_face:

> JustOff suggested 243 translations into Tagalog, Russian, Arabic, Japanese, French, Thai, Bulgarian, Chinese Simplified, Czech, Dutch, English, United Kingdom, German, Greek, Hungarian, Italian, Korean, Polish, Portuguese, Portuguese, Brazilian, Spanish, Spanish, Argentina, Spanish, Mexico, Turkish and Ukrainian

**Comment by JustOff** [comment]
I returned from a short vacation and updated the repository with the latest changes. Almost all language packs are ready, except for Chinese Simplified, which still has several untranslated strings. However, this does not prevent the release, as soon as it is necessary.

I also built and published pre-release versions of language packs on the forum for the final check. Please let me know when you are going to publish to take into account the latest updates, if any will be made by that time.

**Comment by wolfbeast** [comment]
The intended release date for final 28.0.0 is the 16th of August. I'd like to have the final langpacks by Monday.

**Comment by JustOff** [comment]
Language packs are now ready for final versioning, packaging and publishing.

**Comment by wolfbeast** [comment]
Final packaging is completed. Publishing will be done later to minimize the risk of people with idiot configurations getting the langpacks before the browser version 28.

**Comment by JustOff** [comment]
The https://addons.palemoon.org/language-packs/ page also needs to be updated:
  - 27 -> 28
  - forum topic -> https://forum.palemoon.org/viewtopic.php?f=30&t=19474

**Comment by JustOff** [comment]
Looks like everything was done here :tada:
