### ISSUE TITLE
Localize 28.2.0

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/pale-moon-localization#247]
I would prefer to publish 28.2.0 on Tuesday the 13th. Langpack should be ready by Monday EoB for that.

- [x] Fix outstanding strings + verify translations
- [x] Final versioning
- [x] Release packaging run
- [ ] Publish

**Comment by JustOff** [comment]
At the moment all but the Czech, Chinese (Simplified), Portuguese (Brazilian) and Spanish (Argentina) language packs are complete.

Let's give the translators one more day and aim the LPs publication for the Monday. I'll update the issue when ready.

**Comment by wolfbeast** [comment]
Thanks.

**Comment by JustOff** [comment]
Latest updates have been picked up and applied.

**Comment by wolfbeast** [comment]
Published.
