### ISSUE TITLE
UI broken on german language pack since 28.1.0

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/pale-moon-localization#250]
As reported on IRC:

> [16:15] <+Guest88658> interested in a small bug? see: "pale moon / preferences / privacy / use custom settings for history" _with_ localisation via "german.xpi". you'll find the gui to be faulty.
> [16:16] <@MoonchildPM> Guest88658: is your german language pack up to date?
> [16:17] <+Guest88658> oc: 28.2.0, but the bug exists since you've updates de.xpi on 28.1.0

**Comment by JustOff** [comment]
Fixed and verified on Windows, Linux and MacOS.

I think it's worth releasing an out-of-order update.

**Comment by JustOff** [comment]
Btw, do we always have to re-release all LPs when only one of them requires an update?

**Comment by wolfbeast** [comment]
No, we don't
it's simple enough for me to just update only the affected language pack. in this case 28.2.0.1 for DE as out-of-band would be just fine; toss me the XPI when you've updated the install rdf

**Comment by JustOff** [comment]
Here it is: [de-28.2.0.1.zip](https://github.com/MoonchildProductions/pale-moon-localization/files/2590027/de-28.2.0.1.zip).

**Comment by wolfbeast** [comment]
Published
