### ISSUE TITLE
Prepare and publish v28.3.* langpacks

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/pale-moon-localization#254]
What it says on the tin.
Intended release for publishing browser version v28.3.0 is Jan 15th. Langpacks should be done and published before then.

- [x] Fix outstanding strings + verify translations
- [x] Final versioning
- [x] Release packaging run
- [x] Publish

**Comment by JustOff** [comment]
Latest updates have been picked up and applied.

**Comment by wolfbeast** [comment]
Published
