### ISSUE TITLE
Some texts are not Chinese Simplified in zh-CN pack

### ISSUE THREAD

**Issue by leoxxx** [MoonchildProductions/pale-moon-localization#263]
advanced.dtd
```
<!ENTITY captivePortalGroup.label        "補獲的門戶">
<!ENTITY captivePortalDetect.label       "檢測受限的網路訪問">
```

They should be these texts.
```
<!ENTITY captivePortalGroup.label        "强制门户">
<!ENTITY captivePortalDetect.label       "检测受限的网络访问">
```

**Comment by JustOff** [comment]
Сould you please submit your suggestions directly to the  [CrowdIn](https://crowdin.com/project/pale-moon) platform that we use for localization.

You can use your GitHub account to sign, more details are on the [forum](https://forum.palemoon.org/viewtopic.php?p=143886#p143886).

**Comment by leoxxx** [comment]
I've done it.

**Comment by JustOff** [comment]
Thank you, but I noticed that you added and then canceled all your votes against existing translations. Does this mean that you are not sure about your suggestions?  I ask this because with an equal (zero) number of votes, it's uncertain what translation will be included in the language pack.

**Comment by leoxxx** [comment]
NO.Just click it carelessly. I vote it again.

**Comment by JustOff** [comment]
Unfortunately, I do not see the votes [here](https://crowdin.com/translate/pale-moon/293/enus-zhcn#q=captivePortalGroup.label):

![palemoon_2019-06-02_15-41-42](https://user-images.githubusercontent.com/340855/58761428-02f38300-854d-11e9-937f-63f5e4dbb3ef.png)

Since you cannot vote for your choice, you should vote against those that you think are wrong, so that the system will be able to choose the right option when building a language pack.

**Comment by leoxxx** [comment]
I vote the "检测受限的网络访问".
I don't sure the if it's right or not in Traditional Chinese. 補獲的門戶(TC)=捕获门户(SC). It is the direct translation.But I sure my suggestions is right. If you want me to vote one, I'll do it.

**Comment by JustOff** [comment]
Only [captivePortalGroup.label](https://crowdin.com/translate/pale-moon/293/enus-zhcn#q=captivePortalGroup.label) is uncertain, where two translations still have the same number of votes:

![palemoon_2019-06-02_16-02-07](https://user-images.githubusercontent.com/340855/58761703-d2f9af00-854f-11e9-9ef8-18ff4cad045e.png)

**Comment by leoxxx** [comment]
O.K. I vote another one -1. It's the Traditional Chinese. It shouldn't in here.

**Comment by JustOff** [comment]
Thank you for your contribution. These updates will be included into the next version of the zh-CN language pack.
