### ISSUE TITLE
filepicker.dtd missing

### ISSUE THREAD

**Issue by hundertzwei** [MoonchildProductions/pale-moon-localization#274]
Hello,

  I'm using palemoon on linux with the german localization. Since 28.8 I get this error whenever I try to save or open a local file:

----------------------------------------- snip -------------------------------------------------------
XML-Verarbeitungsfehler: Nicht-definierte Entität
Adresse: chrome://global/content/filepicker.xul
Zeile Nr. 25, Spalte 3:  <label value="&lookInMenuList.label;" control="lookInMenuList" accesskey="&lookInMenuList.accesskey;"/>
--^
----------------------------------------- snap -------------------------------------------------------
without the localization there is no problem. After digging around I found, that the string "lookInMenuList.label" is defined in filepicker.dtd, but that is missing from the german localization.

I took filepicker.dtd from palemoon source, and translated it to german with some standard phrases and included it into the langpack-de@palemoon.org.xpi and it worked.

[filepicker.zip](https://github.com/MoonchildProductions/pale-moon-localization/files/4206153/filepicker.zip)

Please include this file.

TIA,
hundertzwei

**Comment by JustOff** [comment]
@mattatobin, could you please take a look at why [filepicker.dtd](https://github.com/MoonchildProductions/UXP/blob/master/toolkit/locales/en-US/chrome/global/filepicker.dtd) is not included in the language pack after `mach package` / `mach langpack`?

**Comment by hundertzwei** [comment]
in [jar.mn](https://github.com/MoonchildProductions/UXP/blob/master/toolkit/locales/jar.mn#L50) there is #ifdef MOZ_GTK around filepicker.dtd.

I think this file gets only included, when the langpack is build with the default tooklit cairo-gtk2 (on linux)

**Comment by JustOff** [comment]
Thank you, I definitely should not be too lazy and figure it out myself. Fortunately, we have a translation of this file for all languages from Pale Moon 27, and it has not changed since then. I will now prepare everything necessary for the out-of-schedule release of language packs that will fix this issue.

**Comment by JustOff** [comment]
@wolfbeast, please issue out-of-schedule release based on [this branch](https://github.com/MoonchildProductions/pale-moon-localization/tree/28.8.1).

**Comment by hundertzwei** [comment]
Thank you.

**Comment by wolfbeast** [comment]
28.8.2 langpacks released

**Comment by JustOff** [comment]
Thank you.
