### ISSUE TITLE
Fix Greek dialog dimensions error

### ISSUE THREAD

**Issue by JustOff** [MoonchildProductions/pale-moon-localization#275]
As [discussed on the forum](https://forum.palemoon.org/viewtopic.php?f=29&t=23942) we need to release a fixed Greek locale from [28.8.x](https://github.com/MoonchildProductions/pale-moon-localization/tree/28.8.x) branch.

**Comment by wolfbeast** [comment]
There are no updates to the locale yet; will that be done by you or...?

**Comment by JustOff** [comment]
They are already there: https://github.com/MoonchildProductions/pale-moon-localization/commits/28.8.x

**Comment by wolfbeast** [comment]
Oh Looking at the wrong branch. I should get some coffee first XD

**Comment by JustOff** [comment]
I obviously should have done the same ... "Greeck" :cry:

**Comment by wolfbeast** [comment]
Ah I see what happened. Maybe you should make a warning in CrowdIn or something that these things are metrics and need to remain untranslated.

**Comment by JustOff** [comment]
I tried to always leave this warning when I saw such strings, but in this case, the entity is used only in MAC builds, so it was missed.

**Comment by wolfbeast** [comment]
Magic wand feature applied! (thanks @mattatobin it's such a time saver!)
